WARNING - api.db - 61 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 195 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 184, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 61 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 195 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 184, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 61 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 195 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 184, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 61 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 195 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 184, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 61 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 195 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 184, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 61 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 195 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 184, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 63 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 197 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 186, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 63 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 197 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 186, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 63 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 197 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 186, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 199 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 188, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 199 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 188, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
WARNING - api.db - 65 - ['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
ERROR - api.db - 199 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 188, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "FOREIGN": syntax error
WARNING - api.db - 65 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=name, type=ParameterSqlType(sql='TEXT'), unique=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=firstName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=lastName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=bornYear, type=SqlType(sql='INTEGER'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=email, type=ParameterSqlType(sql='TEXT'), unique=True, nullable=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=name, type=ParameterSqlType(sql='TEXT'), unique=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=firstName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=lastName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=bornYear, type=SqlType(sql='INTEGER'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=email, type=ParameterSqlType(sql='TEXT'), unique=True, nullable=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=name, type=ParameterSqlType(sql='TEXT'), unique=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=name, type=ParameterSqlType(sql='TEXT'), unique=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=firstName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=lastName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=bornYear, type=SqlType(sql='INTEGER'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=email, type=ParameterSqlType(sql='TEXT'), unique=True, nullable=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=personn_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Personns'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=site_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Website'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=personn_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Personns'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=site_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Website'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=name, type=ParameterSqlType(sql='TEXT'), unique=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 202 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=firstName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=lastName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=bornYear, type=SqlType(sql='INTEGER'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=email, type=ParameterSqlType(sql='TEXT'), unique=True, nullable=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 191, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=name, type=ParameterSqlType(sql='TEXT'), unique=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=personn_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Personns'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=site_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Website'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=firstName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=lastName, type=ParameterSqlType(sql='TEXT'))> ParameterSqlType(sql='TEXT') NOT NULL
<bound method Row.get_row_name of Row(name=bornYear, type=SqlType(sql='INTEGER'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=email, type=ParameterSqlType(sql='TEXT'), unique=True, nullable=True)> ParameterSqlType(sql='TEXT') UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=firstName, type=ParameterSqlType(sql='TEXT'))> TEXT(30) NOT NULL
<bound method Row.get_row_name of Row(name=lastName, type=ParameterSqlType(sql='TEXT'))> TEXT(50) NOT NULL
<bound method Row.get_row_name of Row(name=bornYear, type=SqlType(sql='INTEGER'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=email, type=ParameterSqlType(sql='TEXT'), unique=True, nullable=True)> TEXT(100) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=personn_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Personns'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
<bound method Row.get_row_name of Row(name=site_id, type=SqlType(sql='INTEGER'), foreign_key=functools.partial(<bound method DBTable._get_row of <class 'api.examples.Website'>>, 'id'))> SqlType(sql='INTEGER') NOT NULL
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
<bound method Row.get_row_name of Row(name=id, type=SqlType(sql='INTEGER'), autoincrement=True, unique=True, primary=True)> SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
<bound method Row.get_row_name of Row(name=name, type=ParameterSqlType(sql='TEXT'), unique=True)> TEXT(40) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
name TEXT(40) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "sql": syntax error
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
personn_id SqlType(sql='INTEGER') NOT NULL
site_id SqlType(sql='INTEGER') NOT NULL
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "sql": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id SqlType(sql='INTEGER') AUTOINCREMENT PRIMARY KEY
firstName TEXT(30) NOT NULL
lastName TEXT(50) NOT NULL
bornYear SqlType(sql='INTEGER') NOT NULL
email TEXT(100) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "sql": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id INTEGER AUTOINCREMENT PRIMARY KEY
firstName TEXT(30) NOT NULL
lastName TEXT(50) NOT NULL
bornYear INTEGER NOT NULL
email TEXT(100) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "AUTOINCREMENT": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER AUTOINCREMENT PRIMARY KEY
name TEXT(40) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "AUTOINCREMENT": syntax error
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id INTEGER AUTOINCREMENT PRIMARY KEY
personn_id INTEGER NOT NULL
site_id INTEGER NOT NULL
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "AUTOINCREMENT": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER PRIMARY KEY AUTOINCREMENT
name TEXT(40) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "name": syntax error
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id INTEGER PRIMARY KEY AUTOINCREMENT
personn_id INTEGER NOT NULL
site_id INTEGER NOT NULL
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "personn_id": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 207 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id INTEGER PRIMARY KEY AUTOINCREMENT
firstName TEXT(30) NOT NULL
lastName TEXT(50) NOT NULL
bornYear INTEGER NOT NULL
email TEXT(100) UNIQUE
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 196, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "firstName": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 208 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT(40) UNIQUE, 
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 197, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
WARNING - api.db - 68 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'parent', 'validate']
ERROR - api.db - 208 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
firstName TEXT(30) NOT NULL, 
lastName TEXT(50) NOT NULL, 
bornYear INTEGER NOT NULL, 
email TEXT(100) UNIQUE, 
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 197, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
ERROR - api.db - 208 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
personn_id INTEGER NOT NULL, 
site_id INTEGER NOT NULL, 
FOREIGN KEY (personn_id,site_id 
REFERENCES (id,id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 197, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
WARNING - api.db - 71 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 213 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
firstName TEXT(30) NOT NULL, 
lastName TEXT(50) NOT NULL, 
bornYear INTEGER NOT NULL, 
email TEXT(100) UNIQUE, 
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 202, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
WARNING - api.db - 71 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 213 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT(40) UNIQUE, 
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 202, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
ERROR - api.db - 213 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
personn_id INTEGER NOT NULL, 
site_id INTEGER NOT NULL, 
FOREIGN KEY (personn_id,site_id 
REFERENCES (Personns.id,Website.id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 202, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
WARNING - api.db - 71 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 213 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
firstName TEXT(30) NOT NULL, 
lastName TEXT(50) NOT NULL, 
bornYear INTEGER NOT NULL, 
email TEXT(100) UNIQUE, 
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 202, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
WARNING - api.db - 71 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 213 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT(40) UNIQUE, 
FOREIGN KEY ( 
REFERENCES ())
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 202, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
ERROR - api.db - 213 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
personn_id INTEGER NOT NULL, 
site_id INTEGER NOT NULL, 
FOREIGN KEY (personn_id,site_id 
REFERENCES (Personns.id,Website.id))
ON UPDATE CASCADE
ON DELETE RESTRICT
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 202, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "REFERENCES": syntax error
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 228 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT(40) UNIQUE, 
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 217, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ")": syntax error
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 228 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT(40) UNIQUE, 
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 217, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ")": syntax error
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 228 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
firstName TEXT(30) NOT NULL, 
lastName TEXT(50) NOT NULL, 
bornYear INTEGER NOT NULL, 
email TEXT(100) UNIQUE, 
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 217, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ")": syntax error
ERROR - api.db - 228 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
personn_id INTEGER NOT NULL, 
site_id INTEGER NOT NULL, 
FOREIGN KEY (personn_id) REFERENCES <class 'api.examples.Personns'>(id ) ON UPDATE CASCADE ON DELETE RESTRICT, 
FOREIGN KEY (site_id) REFERENCES <class 'api.examples.Website'>(id ) ON UPDATE CASCADE ON DELETE RESTRICT, 
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 217, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 227 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS personns (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
firstName TEXT(30) NOT NULL, 
lastName TEXT(50) NOT NULL, 
bornYear INTEGER NOT NULL, 
email TEXT(100) UNIQUE, 
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 216, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ")": syntax error
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 227 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS website (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT(40) UNIQUE, 
) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 216, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ")": syntax error
ERROR - api.db - 227 - Unhandled error in execute for CREATE TABLE IF NOT EXISTS inscriptions (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
personn_id INTEGER NOT NULL, 
site_id INTEGER NOT NULL, 
FOREIGN KEY (personn_id) REFERENCES <class 'api.examples.Personns'>(id ) ON UPDATE CASCADE ON DELETE RESTRICT, 
FOREIGN KEY (site_id) REFERENCES <class 'api.examples.Website'>(id ) ON UPDATE CASCADE ON DELETE RESTRICT) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 216, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 86 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 86 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 85 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 85 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 85 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 85 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 85 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 85 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 82 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 82 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 82 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 82 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 77 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 77 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 78 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 78 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 77 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 77 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 78 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 78 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 81 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 81 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 81 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 81 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (dict_keys(['firstName', 'lastName', 'email'])) VALUES (dict_values(['Arthur', 'WOELFEL', 'woelfel.arthur@gmail.com'])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (dict_keys(['firstName', 'lastName', 'email'])) VALUES (dict_values(['Pierre', 'MAILLE', 'pmaille75@gmail.com'])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (dict_keys(['name'])) VALUES (dict_values(['amazon'])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (dict_keys(['name'])) VALUES (dict_values(['Le Bon Coin'])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (dict_keys(['name'])) VALUES (dict_values(['Troll2jeux'])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (dict_keys(['personn_id', 'site_id'])) VALUES (dict_values([None, None])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (dict_keys(['personn_id', 'site_id'])) VALUES (dict_values([None, None])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (dict_keys(['personn_id', 'site_id'])) VALUES (dict_values([None, None])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (dict_keys(['personn_id', 'site_id'])) VALUES (dict_values([None, None])) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email) VALUES (ArthurWOELFELwoelfel.arthur@gmail.com) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "@gmail": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email) VALUES (PierreMAILLEpmaille75@gmail.com) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "@gmail": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (name) VALUES (amazon) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: amazon
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (name) VALUES (Le Bon Coin) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "Bon": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (name) VALUES (Troll2jeux) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: Troll2jeux
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email) VALUES (Arthur, WOELFEL, woelfel.arthur@gmail.com) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "@gmail": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email) VALUES (Pierre, MAILLE, pmaille75@gmail.com) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "@gmail": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (name) VALUES (amazon) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: amazon
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (name) VALUES (Le Bon Coin) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "Bon": syntax error
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Website (name) VALUES (Troll2jeux) with parameters ()
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: Troll2jeux
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email) VALUES (?, ?, ?) with parameters ('Arthur', 'WOELFEL', 'woelfel.arthur@gmail.com')
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: personns.bornYear
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email) VALUES (?, ?, ?) with parameters ('Pierre', 'MAILLE', 'pmaille75@gmail.com')
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: personns.bornYear
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 244 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 76 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email, bornYear) VALUES (?, ?, ?, ?) with parameters ('Arthur', 'WOELFEL', 'woelfel.arthur@gmail.com', 2007)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: personns.email
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Personns (firstName, lastName, email, bornYear) VALUES (?, ?, ?, ?) with parameters ('Pierre', 'MAILLE', 'pmaille75@gmail.com', 2007)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: personns.email
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Website (name) VALUES (?) with parameters ('amazon',)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: website.name
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Website (name) VALUES (?) with parameters ('Le Bon Coin',)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: website.name
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Website (name) VALUES (?) with parameters ('Troll2jeux',)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: website.name
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
ERROR - api.db - 245 - Unhandled error in execute for INSERT INTO Inscriptions (personn_id, site_id) VALUES (?, ?) with parameters (None, None)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 233, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: inscriptions.personn_id
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 79 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
ERROR - api.db - 263 - Unhandled error in execute for SELECT * WHERE ? = ? AND ? = ? AND ? = ? AND ? = ? with parameters ('firstName', 'Arthur', 'lastName', 'WOELFEL', 'email', 'woelfel.arthur@gmail.com', 'bornYear', 2007)
Traceback (most recent call last):
  File "C:\Users\arthu\python\web\TaskManager\api\db.py", line 245, in execute
    r = conn.execute(command, params_tuple)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no tables specified
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 80 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 81 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
WARNING - api.db - 81 - ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_autoincrement', '_foreign_key', '_name', '_nullable', '_primary', '_type', '_unique', 'get_foreign_key', 'get_row_name', 'get_row_type', 'is_autoincrement', 'is_nullable', 'is_primary', 'is_unique', 'match_with', 'multiple', 'table', 'validate']
